version: "3.9"
services:
  sprachtandem:
    build:
      context: . 
      dockerfile: ./Dockerfile
    entrypoint: ./start.sh
    volumes:
      - .:/sprachtandem
      - bundle_path:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - ./envs/database_development.env


volumes:
  bundle_path: 
  postgres_db: