version: "3.9"
services:
  sprachtandem:
    build:
      context: . 
      dockerfile: ./Dockerfile
    entrypoint: ./start.sh
    volumes:
      - .:/sprachtandem
      - bundle_path:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - ./envs/database_development.env
    ports:
      - "5432:5432"

  redis:
    image: 'redis:5-alpine'
    ports:
      - "6379:6379"

volumes:
  bundle_path: 
  postgres_db: